### ISSUE TITLE
Please, use the UTF8 encoding for buckets and files names!

### ISSUE THREAD

**Issue by AlexeyALeonov** [Storj/libstorj#356] opened 2017-06-15 06:17 UTC
All non-English and non-US countries have a some troubles with Windows and encodings.
Very often for console Windows uses a local codepage, for GUI - other codepage, for filesystem UTF8.
For example, for Russian: native CMD codepage 866, for PowerShell codepage 1251, for filesystem Unicode.

Storj-js can deal with it and store bucket and file names in UTF8 only. So I be able upload and download in any current codepage and get a normal Russian names for buckets and files.

Libstorj somehow converting UTF8 to the Default encoding and store names in Default encoding. This is look normal only if current codepage tied with Default system encoding (i.e. 1251 for my example), in others cases it's looking broken.
Second problem, when i trying compare names, which i got from Libstorj, they didn't match names from filesystem even current codepage is Default, because names from filesystem in UTF8!

So, I'd like that Libstorj do not trying to convert from UTF8 to Default encoding and uses UTF8 as is.

Now, I can workaround names (for bucket name only) with this expression:
`$folder = [System.Text.Encoding]::Default.GetString([System.Text.Encoding]::UTF8.GetBytes($dir.Basename));`
This trick forcing the Libstorj using a UTF8 encoding for bucket's names instead of Default encoding.
But I can't do the same with filenames, because for system this would be wrong encoding and file not be found.

For example I trying create a bucket with Russian name "Алёна": 
```
PS Z:\> chcp 65001
Active code page: 65001

PS Z:\> ~\storj.exe add-bucket Алёна
ID: 1effeba3d85cb3632f8f4581    Decrypted: true         Name: ����

PS Z:\> ~\storj.exe list-buckets
ID: 1effeba3d85cb3632f8f4581    Decrypted: true         Created: 2017-06-15T06:01:42.533Z       Name: ����

PS Z:\> chcp 1251
Текущая кодовая страница: 1251

PS Z:\> ~\storj.exe list-buckets
ID: 1effeba3d85cb3632f8f4581    Decrypted: true         Created: 2017-06-15T06:01:42.533Z       Name: Алёна
```
In that example we saw, that current codepage involve in name encoding for view. This is only can be, if encoding was not UTF8 for names.
same example for storj-js:
```
C:\Users>chcp 65001
Active code page: 65001

C:\Users>storj add-bucket Алёна
 [Thu Jun 15 2017 09:14:34 GMT+0300 (RTZ 2 (зима))] [info]   ID: a0247a31825a18c0ea7f7982, Name: Алёна, Storage: 0, Transfer: 0, Public:

C:\Users>chcp 1251
Текущая кодовая страница: 1251

C:\Users>storj list-buckets
 [Thu Jun 15 2017 09:16:25 GMT+0300 (RTZ 2 (зима))] [info]   ID: a0247a31825a18c0ea7f7982, Name: Алёна, Storage: 0, Transfer: 0, Public:
```
Name is the same for any current codepage.

**Comment by AlexeyALeonov** [comment] 2017-06-15 07:57
I'm found working workaround for PowerShell:
`[System.Console]::OutputEncoding = [System.Text.Encoding]::UTF8;`
In that case comparing Name of the bucket with Name of the folder is correct.
But hash of the Russian bucket name not the same which was in storj-js. Why is that?

**Comment by braydonf** [comment] 2017-06-15 12:08
Duplicate of https://github.com/Storj/libstorj/issues/147

**Closed** 2017-06-15 12:15 UTC
