### ISSUE TITLE
Large file size upload failure 

### ISSUE THREAD

**Issue by MeijeSibbel** [Storj/libstorj#254] opened 2017-03-19 13:19 UTC
I did some more digging and now i am confident enough to open a issue about this as i am certain there is a problem.

### My observations:

(All uploaded files are dummy .zip files)

**When the upload works:**

- When i start a new upload, task-manger shows that my intel-i7 is being used at 100% and that my disk is being read at 20MB/s, after the read process is completed it moves onto the challenges step:

```
{"message": "Successfully retrieved frame id", "level": 3, "timestamp": 1489923220899}
{"message": "Shard (0) hash: dc59d9de396087b32c1ac97b2f377d1840637840", "level": 3, "timestamp": 1489923506903}
{"message": "Challenges for shard index 0", "level": 4, "timestamp": 1489923506903}
{"message": "Shard 0 Challenge [0]: 70abf1c888934dab7fd9d60be8178cc6", "level": 4, "timestamp": 1489923506903}
{"message": "Shard 0 Challenge [1]: d6754d03657fbb1d361580cb9309e09b", "level": 4, "timestamp": 1489923506903}
{"message": "Shard 0 Challenge [2]: 16c64d332ffbc7697d09ff9fd1b8c376", "level": 4, "timestamp": 1489923506903}
{"message": "Shard 0 Challenge [3]: af3a06386f41dc09f84c7b9b991c180a", "level": 4, "timestamp": 1489923506903}
```
- For comparison it takes less than a minute for a 30GB upload to start on my machine.

**When the upload does not work:**

- When i start a new upload, the task-manager shows that my intel-i7 is being use at 100%, my disk is being read at 20MB/s for a minute, then the disk reading stops, the CPU usage is still 100% but the upload never starts and hangs here:

```
C:\libstorj-1.0.0-beta4\bin>storj --debug upload-file 269d91962d5a76bd628864b6 D:\40GB.zip
{"message": "Checking if bucket id [269d91962d5a76bd628864b6] exists", "level": 3, "timestamp": 1489927861689}
{"message": "Checking if file id [cd836228dd0ca1fcbfa33505] already exists...", "level": 3, "timestamp": 1489927862119}
{"message": "[40GB.zip] Requesting file staging frame... (retry: 0)", "level": 3, "timestamp": 1489927862119}
{"message": "Creating frame for shard index 4", "level": 3, "timestamp": 1489927862120}
{"message": "Creating frame for shard index 6", "level": 3, "timestamp": 1489927862120}
{"message": "Creating frame for shard index 3", "level": 3, "timestamp": 1489927862120}
{"message": "Creating frame for shard index 0", "level": 3, "timestamp": 1489927862120}
{"message": "Creating frame for shard index 9", "level": 3, "timestamp": 1489927862120}
{"message": "Creating frame for shard index 7", "level": 3, "timestamp": 1489927862120}
{"message": "Creating frame for shard index 8", "level": 3, "timestamp": 1489927862121}
{"message": "Creating frame for shard index 2", "level": 3, "timestamp": 1489927862120}
{"message": "Creating frame for shard index 5", "level": 3, "timestamp": 1489927862120}
{"message": "Creating frame for shard index 1", "level": 3, "timestamp": 1489927862120}
{"message": "fn[request_frame_id] - JSON Response: { "user": "meije@storj.io", "shards": [ ], "size": 0, "locked": false, "created": "2017-03-19T12:51:02.509Z", "id": "58ce7eb6a0338e3626e956d9" }", "level": 4, "timestamp": 1489927862590}
{"message": "Successfully retrieved frame id", "level": 3, "timestamp": 1489927862614}
```
- It does not just hang a few minutes, it will never finish, the 40GB upload above has been hanging  for 24 hours at 100% CPU usage!,

- My 1TB file has been running at 100% CPU usage for 48 hours, it still does not start.

- I have tried uploading files in a ste-up of 10GB (10GB-20GB-30GB-40GB...), the upload fails at the 40GB file, while the upload succeeds for a 30GB file, thus the failure occurs for files somewhere between 30GB-40GB in size.

### Discussion:

- It is impossible that a 30GB file starts uploading in less than a minute but a 40GB file hangs for more than 24 hours, this is just not possible. Something is definitely wrong and it is for this reason that i open this issue.

**Comment by braydonf** [comment] 2017-03-19 14:23
Thanks for the info. What's the maximum read speed of the drive, sequential and random? At 20MB/s it would take 25min to read the 30GB file from disk, and 14 hours for 1TB.

**Comment by braydonf** [comment] 2017-03-19 14:41
Also which release are you using? 32bit or 64?

**Comment by MeijeSibbel** [comment] 2017-03-19 14:44
I am using the 64bit version, do you know a tool for windows to test these read speeds?,

**Comment by braydonf** [comment] 2017-03-19 14:46
Okay, we can try to reproduce based on this info. I don't know of a tool off hand for benchmarking on windows.

**Comment by MeijeSibbel** [comment] 2017-03-19 14:52
@braydonf : 
[CDM_20170319155156.txt](https://github.com/Storj/libstorj/files/853251/CDM_20170319155156.txt)

**Comment by braydonf** [comment] 2017-03-19 14:54
Okay, thanks. I've noticed CrytalDiskMark used for various reviews on Windows.

**Comment by MeijeSibbel** [comment] 2017-03-19 14:55
yeah, i used it for this test

**Comment by braydonf** [comment] 2017-03-19 14:58
There is a huge difference in performance with sequential vs random, we should optimize w/ sequential reads for the initial hashing of challenge generation.

**Comment by MeijeSibbel** [comment] 2017-03-19 15:02
For comparison, here is the benchmark using my main SSD - OS drive ( the file is not located on this drive though): 
[CDM_20170319160042.txt](https://github.com/Storj/libstorj/files/853257/CDM_20170319160042.txt)

**Comment by braydonf** [comment] 2017-03-19 15:06
Another optimization would be to use "Partial Audits" (https://storj.io/storj.pdf) and only hash a part of each shard, which may be a good idea from the farmer side as well.

**Comment by Th3Van** [comment] 2017-03-19 16:39
I tried to single-upload three 100GB files today using beta4 (64bit). 10 min. after executing each of the storj commands, it started to upload 25 shards.. each 4.294.967.296 Bytes in size.. But all three uploads failed..

*CPU*
![nwzvogu3d9a6iygmum5eribe8q7kcro9 100g strojlib-testfile](https://cloud.githubusercontent.com/assets/18688983/24081992/7b4ba51c-0cbe-11e7-84aa-834d173fcbac.png)
**Shard size**
Correct me if i am wrong, but as i understands it, a farmer has to allocate at least (256 x 4.3GB) ~1100GB HDD space using storjshare-daemon/GUI to send a offer for shards at this size. Every farmers allocated space will be divided by 256 and can't receive a single shard bigger than that. -> https://github.com/Storj/libstorj/issues/254
Uploading even bigger files (e.g. 1TB) and shards will get equally bigger, resulting in just a few or no farmers at all sending a OFFER due to not enough allocated space.

**Log File**
This is my own theory, but studding the log file, it seems like the shards are uploading fine, but if they somehow get disconnected, or the tunnel that the farmer are using drops, storj is having a very hard time to cancel the current upload and queue the bridge for a new farmer.

[NWZvoGU3D9A6IyGMuM5eRIBE8Q7KCro9.100G.strojlib-testfile.txt](https://github.com/Storj/libstorj/files/853308/NWZvoGU3D9A6IyGMuM5eRIBE8Q7KCro9.100G.strojlib-testfile.txt) - Upload failure: Farmer request error 
[pzvzTW1sedVKCUiV5IggcM9CaQfSGq49.100G.strojlib-testfile.txt](https://github.com/Storj/libstorj/files/853309/pzvzTW1sedVKCUiV5IggcM9CaQfSGq49.100G.strojlib-testfile.txt) - longjmp causes uninitialized stack frame
[h6vlX2RkefMVBrhk37iIV9oXnuqKuyw7.100G.strojlib-testfile.txt](https://github.com/Storj/libstorj/files/853320/h6vlX2RkefMVBrhk37iIV9oXnuqKuyw7.100G.strojlib-testfile.txt) - Upload failure: Farmer request error

**Storj Options**
While storj are in beta stage, it would be great if options like `shards size, maximum number of cpu/kernels to be using, concurrent sends, Hash read threads, etc.` would be added. 😃 

//Th3Van

**Comment by braydonf** [comment] 2017-03-19 16:56
Thanks for the info, for the first log: it looks like there were several retries to upload shards after various errors including: `CURLE_SEND_ERROR` (6 times), `CURLE_COULDNT_CONNECT` (6 times), `CURLE_RECV_ERROR` (3 times), `CURLE_UNSUPPORTED_PROTOCOL` (3 times) and the exclude list was expanded during the retries correctly.

**Comment by braydonf** [comment] 2017-03-19 17:13
The second and third logs, it looks like all retries were used and it stopped trying to upload.

For the third log the majority of the errors being: `CURLE_SEND_ERROR` (15 times), `CURLE_UNSUPPORTED_PROTOCOL` (4 times), `CURLE_RECV_ERROR` (2 times), `CURLE_COULDNT_CONNECT` (1 time).

For the second log: `CURLE_SEND_ERROR` (20 times), `CURLE_COULDNT_CONNECT` (11 times), `CURLE_UNSUPPORTED_PROTOCOL` (4 times), `CURLE_RECV_ERROR` (3 times).

**Comment by braydonf** [comment] 2017-03-19 17:17
> Every farmers allocated space will be divided by 256 and can't receive a single shard bigger than that.

That would be good to verify on the farmer side. I'm not sure of the details there.

**Comment by Th3Van** [comment] 2017-03-19 17:29
Logfile from a 1TB upload i tried yesterday, but also failed :

[273js238hf43j2s37f3h2834.storj-c-lib.testfile.1000000M.txt](https://github.com/Storj/libstorj/files/853390/273js238hf43j2s37f3h2834.storj-c-lib.testfile.1000000M.Th3Van.txt) - longjmp causes uninitialized stack frame

**Comment by braydonf** [comment] 2017-03-19 18:01
Great thanks, good to see that it started to upload. Looks like the `longjmp` issue is causing repeat problems.

**Comment by braydonf** [comment] 2017-03-20 21:29
https://github.com/Storj/libstorj/pull/255 has been merged that will help with preparing shards when reading from disks with fast sequential read performance and not random (a.ka. spinning disks). This should resolve @MeijeSibbel issue. From tests that @aleitner ran there was a huge increase in performance.

**Comment by braydonf** [comment] 2017-03-21 23:00
@Th3Van what version of libc is running, what's the output of running `./lib/x86_64-linux-gnu/libc.so.6`

**Comment by Th3Van** [comment] 2017-03-21 23:58
root@Server025:/tmp# /lib/x86_64-linux-gnu/libc.so.6 
```
GNU C Library (Debian GLIBC 2.24-9) stable release version 2.24, by Roland McGrath et al.
Copyright (C) 2016 Free Software Foundation, Inc.
This is free software; see the source for copying conditions.
There is NO warranty; not even for MERCHANTABILITY or FITNESS FOR A
PARTICULAR PURPOSE.
Compiled by GNU CC version 6.3.0 20161229.
Available extensions:
        crypt add-on version 2.1 by Michael Glad and others
        GNU Libidn by Simon Josefsson
        Native POSIX Threads Library by Ulrich Drepper et al
        BIND-8.2.3-T5B
libc ABIs: UNIQUE IFUNC
For bug reporting instructions, please see:
<http://www.debian.org/Bugs/>.
```

**Comment by braydonf** [comment] 2017-03-22 00:18
Okay thanks. We haven't been able to reproduce the `longjump` issue yet.

Most issues reported involving this error code are related to libcurl, and greping through all the dependencies and `siglongjmp` is only used within libcurl. The issue looks to be related to synchronous dns handling and signal handling, compiling with async dns resolving looks to be [the fix](http://stackoverflow.com/questions/9191668/error-longjmp-causes-uninitialized-stack-frame).

I've include this with https://github.com/Storj/libstorj/pull/258

**Comment by braydonf** [comment] 2017-03-22 18:32
Okay these issues other than those related to `CURLE_SEND_ERROR` which will likely need to be handled on the farmer side should me solved with:
- https://github.com/Storj/libstorj/pull/255
- https://github.com/Storj/libstorj/pull/258

If there are any issues we can reopen.

**Comment by Th3Van** [comment] 2017-03-22 21:28
Just tried 100GB file again using RC1, and it failed with `Bridge request error`

[AkSkxKvUNVn54ygnHwx7gihc7oIpGjxo.100G.strojlib-testfile.txt](https://github.com/Storj/libstorj/files/862926/AkSkxKvUNVn54ygnHwx7gihc7oIpGjxo.100G.strojlib-testfile.txt)

I'm seeing a few `Failed to push shard xx... Retrying...` following by `Put shard request error code: xx`  but for some reason it's not retrying.. it just sits there with no CPU or HDD activity for some minutes, and finally dumps the `Cleaning up shard xx / Pointers  xx` and quits with the `Bridge request error` message..

**Comment by braydonf** [comment] 2017-03-22 23:32
It likely tried to retry, but then was unable to get a new offer after several attempts.

**Comment by braydonf** [comment] 2017-03-22 23:33
It likely tried to retry, but then was unable to get a new offer after several attempts.

**Comment by braydonf** [comment] 2017-03-23 01:41
Sounds like there may be some additional issues that need to be reproduced, see https://community.storj.io/channel/core

**Comment by Th3Van** [comment] 2017-03-23 13:21
Tried to uploading the 1TB file again, but failed with `Bridge request error` aka to many failed retries..
Either the retry limit has to be higher, or the shards has to be smaller in sizes to get this to work ?...

[bhsVKAoVgtRcyVdJz1DDhrTL0peiTvD0.1000G.strojlib-testfile.txt](https://github.com/Storj/libstorj/files/864783/bhsVKAoVgtRcyVdJz1DDhrTL0peiTvD0.1000G.strojlib-testfile.txt)

**Comment by Th3Van** [comment] 2017-03-23 16:36
Just did a 50GB file with success
[FFsxwuzI73wbFKvXq7rLe8tvSDENqH4E.50G.strojlib-testfile.txt](https://github.com/Storj/libstorj/files/865398/FFsxwuzI73wbFKvXq7rLe8tvSDENqH4E.50G.strojlib-testfile.txt)
Using libstorj-1.0.0-rc1-linux64 on Debian.

**Comment by Th3Van** [comment] 2017-03-23 21:26
Looking at the mirrors of the shards, there seems to be missing quite a few established mirrors.. could be related to the size of the shards 😄 

[FFsxwuzI73wbFKvXq7rLe8tvSDENqH4E.50G.strojlib-testfile.mirrors.txt](https://github.com/Storj/libstorj/files/866234/FFsxwuzI73wbFKvXq7rLe8tvSDENqH4E.50G.strojlib-testfile.mirrors.txt)
- File size : `50 GB`
- Shards : `12`
- Established mirrors : `28 of 60`
- avg. mirrors pr. shard : `2,33`

[dyjAVIcsYjDQyctN292IkpJrcHWyrEac.100G.strojlib-testfile.mirrors.txt](https://github.com/Storj/libstorj/files/866235/dyjAVIcsYjDQyctN292IkpJrcHWyrEac.100G.strojlib-testfile.mirrors.txt)
- File size : `100 GB`
- Shards : `25`
- Established mirrors : `33 of 125`
- avg. mirrors pr. shard : `1,32`

Currently uploading a 250GB file. Going to post the mirror stats when/if it's done.

**Comment by aleitner** [comment] 2017-03-23 21:50
yup we plan on working on this. See https://github.com/Storj/libstorj/issues/249

**Closed** 2017-03-30 19:40 UTC
